# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FenetrePrincipale.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Homepage(object):
    def setupUi(self, Homepage):
        Homepage.setObjectName("Homepage")
        Homepage.resize(723, 495)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Homepage.sizePolicy().hasHeightForWidth())
        Homepage.setSizePolicy(sizePolicy)
        self.widgetCentral = QtWidgets.QWidget(Homepage)
        self.widgetCentral.setStyleSheet("*{\n"
"    color:#000;\n"
"    border:none;\n"
"}\n"
"QPushButton{\n"
"    padding: 9px 5px;\n"
"    text-align: left;\n"
"}\n"
"#menuGauche{\n"
"    background-color: #65132d;\n"
"}\n"
"#accueilBtn{\n"
"    background-color:#e5e5e5;\n"
"    padding: 10px 5px;\n"
"    text-align: left;\n"
"    border-top-left-radius: 15px;\n"
"}\n"
"#reglagesBtn, #renommageBtn, #sauvegardeBtn, #triBtn{\n"
"    color: #ffffff;\n"
"}\n"
"#partiePrincipale{\n"
"    background-color: #e5e5e5;\n"
"}\n"
"#carte1, #carte2, #carte3, #carte4{\n"
"    background-color:#ffffff;\n"
"    border-radius:20px;\n"
"}\n"
"#widgetInstagram, #widgetEvenement{\n"
"    background-color:#ffffff;\n"
"    border-radius:10px;\n"
"}\n"
"#ajouterInstaBtn, #ajouterEventBtn{\n"
"    color: #ffffff;    \n"
"    background-color: #65132d;\n"
"    border-radius: 18px;\n"
"}\n"
"#ajouterInstaBtn:pressed, #ajouterEventBtn:pressed{\n"
"    background-color: #ffffff;\n"
"    color: black;\n"
"}")
        self.widgetCentral.setObjectName("widgetCentral")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widgetCentral)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.menuGauche = QtWidgets.QWidget(self.widgetCentral)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.menuGauche.sizePolicy().hasHeightForWidth())
        self.menuGauche.setSizePolicy(sizePolicy)
        self.menuGauche.setStyleSheet("")
        self.menuGauche.setObjectName("menuGauche")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.menuGauche)
        self.horizontalLayout_4.setContentsMargins(10, 18, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.frameMenu = QtWidgets.QFrame(self.menuGauche)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameMenu.sizePolicy().hasHeightForWidth())
        self.frameMenu.setSizePolicy(sizePolicy)
        self.frameMenu.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameMenu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameMenu.setObjectName("frameMenu")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.frameMenu)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.accueilBtn = QtWidgets.QPushButton(self.frameMenu)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.accueilBtn.setFont(font)
        self.accueilBtn.setIconSize(QtCore.QSize(20, 20))
        self.accueilBtn.setObjectName("accueilBtn")
        self.verticalLayout_11.addWidget(self.accueilBtn)
        self.triBtn = QtWidgets.QPushButton(self.frameMenu)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.triBtn.setFont(font)
        self.triBtn.setObjectName("triBtn")
        self.verticalLayout_11.addWidget(self.triBtn)
        self.renommageBtn = QtWidgets.QPushButton(self.frameMenu)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.renommageBtn.setFont(font)
        self.renommageBtn.setObjectName("renommageBtn")
        self.verticalLayout_11.addWidget(self.renommageBtn)
        self.sauvegardeBtn = QtWidgets.QPushButton(self.frameMenu)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.sauvegardeBtn.setFont(font)
        self.sauvegardeBtn.setObjectName("sauvegardeBtn")
        self.verticalLayout_11.addWidget(self.sauvegardeBtn)
        self.reglagesBtn = QtWidgets.QPushButton(self.frameMenu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.reglagesBtn.sizePolicy().hasHeightForWidth())
        self.reglagesBtn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.reglagesBtn.setFont(font)
        self.reglagesBtn.setObjectName("reglagesBtn")
        self.verticalLayout_11.addWidget(self.reglagesBtn)
        self.horizontalLayout_4.addWidget(self.frameMenu, 0, QtCore.Qt.AlignTop)
        self.horizontalLayout.addWidget(self.menuGauche)
        self.partiePrincipale = QtWidgets.QWidget(self.widgetCentral)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.partiePrincipale.sizePolicy().hasHeightForWidth())
        self.partiePrincipale.setSizePolicy(sizePolicy)
        self.partiePrincipale.setObjectName("partiePrincipale")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.partiePrincipale)
        self.verticalLayout.setContentsMargins(10, 0, 10, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frameEnTete = QtWidgets.QWidget(self.partiePrincipale)
        self.frameEnTete.setObjectName("frameEnTete")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frameEnTete)
        self.horizontalLayout_2.setContentsMargins(0, 18, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.labelEnTete = QtWidgets.QLabel(self.frameEnTete)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelEnTete.sizePolicy().hasHeightForWidth())
        self.labelEnTete.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Savoye LET")
        font.setPointSize(69)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.labelEnTete.setFont(font)
        self.labelEnTete.setTextFormat(QtCore.Qt.AutoText)
        self.labelEnTete.setScaledContents(False)
        self.labelEnTete.setObjectName("labelEnTete")
        self.horizontalLayout_2.addWidget(self.labelEnTete, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout.addWidget(self.frameEnTete, 0, QtCore.Qt.AlignTop)
        self.frameCartes = QtWidgets.QWidget(self.partiePrincipale)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameCartes.sizePolicy().hasHeightForWidth())
        self.frameCartes.setSizePolicy(sizePolicy)
        self.frameCartes.setObjectName("frameCartes")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frameCartes)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 5)
        self.horizontalLayout_7.setSpacing(20)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.carte1 = QtWidgets.QFrame(self.frameCartes)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.carte1.sizePolicy().hasHeightForWidth())
        self.carte1.setSizePolicy(sizePolicy)
        self.carte1.setMinimumSize(QtCore.QSize(160, 0))
        self.carte1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.carte1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.carte1.setObjectName("carte1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.carte1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frameCarte1 = QtWidgets.QFrame(self.carte1)
        self.frameCarte1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameCarte1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameCarte1.setObjectName("frameCarte1")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frameCarte1)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.labelDisplayCarte1 = QtWidgets.QLabel(self.frameCarte1)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.labelDisplayCarte1.setFont(font)
        self.labelDisplayCarte1.setObjectName("labelDisplayCarte1")
        self.horizontalLayout_8.addWidget(self.labelDisplayCarte1)
        self.verticalLayout_2.addWidget(self.frameCarte1, 0, QtCore.Qt.AlignTop)
        self.labelCarte1 = QtWidgets.QLabel(self.carte1)
        self.labelCarte1.setObjectName("labelCarte1")
        self.verticalLayout_2.addWidget(self.labelCarte1, 0, QtCore.Qt.AlignTop)
        self.horizontalLayout_7.addWidget(self.carte1)
        self.carte2 = QtWidgets.QFrame(self.frameCartes)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.carte2.sizePolicy().hasHeightForWidth())
        self.carte2.setSizePolicy(sizePolicy)
        self.carte2.setMinimumSize(QtCore.QSize(160, 0))
        self.carte2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.carte2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.carte2.setObjectName("carte2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.carte2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frameCarte2 = QtWidgets.QFrame(self.carte2)
        self.frameCarte2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameCarte2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameCarte2.setObjectName("frameCarte2")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.frameCarte2)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.labelDisplayCarte2 = QtWidgets.QLabel(self.frameCarte2)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.labelDisplayCarte2.setFont(font)
        self.labelDisplayCarte2.setObjectName("labelDisplayCarte2")
        self.horizontalLayout_9.addWidget(self.labelDisplayCarte2)
        self.verticalLayout_3.addWidget(self.frameCarte2, 0, QtCore.Qt.AlignTop)
        self.labelCarte2 = QtWidgets.QLabel(self.carte2)
        self.labelCarte2.setObjectName("labelCarte2")
        self.verticalLayout_3.addWidget(self.labelCarte2, 0, QtCore.Qt.AlignTop)
        self.horizontalLayout_7.addWidget(self.carte2)
        self.carte3 = QtWidgets.QFrame(self.frameCartes)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.carte3.sizePolicy().hasHeightForWidth())
        self.carte3.setSizePolicy(sizePolicy)
        self.carte3.setMinimumSize(QtCore.QSize(160, 0))
        self.carte3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.carte3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.carte3.setObjectName("carte3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.carte3)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frameCarte3 = QtWidgets.QFrame(self.carte3)
        self.frameCarte3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameCarte3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameCarte3.setObjectName("frameCarte3")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.frameCarte3)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.labelDisplayCarte3 = QtWidgets.QLabel(self.frameCarte3)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.labelDisplayCarte3.setFont(font)
        self.labelDisplayCarte3.setObjectName("labelDisplayCarte3")
        self.horizontalLayout_10.addWidget(self.labelDisplayCarte3)
        self.verticalLayout_4.addWidget(self.frameCarte3, 0, QtCore.Qt.AlignTop)
        self.labelCarte3 = QtWidgets.QLabel(self.carte3)
        self.labelCarte3.setObjectName("labelCarte3")
        self.verticalLayout_4.addWidget(self.labelCarte3, 0, QtCore.Qt.AlignTop)
        self.horizontalLayout_7.addWidget(self.carte3)
        self.verticalLayout.addWidget(self.frameCartes, 0, QtCore.Qt.AlignHCenter)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout.addWidget(self.partiePrincipale)
        Homepage.setCentralWidget(self.widgetCentral)

        self.retranslateUi(Homepage)
        QtCore.QMetaObject.connectSlotsByName(Homepage)

    def retranslateUi(self, Homepage):
        _translate = QtCore.QCoreApplication.translate
        Homepage.setWindowTitle(_translate("Homepage", "MainWindow"))
        self.accueilBtn.setText(_translate("Homepage", "  Accueil"))
        self.triBtn.setText(_translate("Homepage", "Tri"))
        self.renommageBtn.setText(_translate("Homepage", "Renommage    "))
        self.sauvegardeBtn.setText(_translate("Homepage", "Sauvegarde"))
        self.reglagesBtn.setText(_translate("Homepage", "Réglages"))
        self.labelEnTete.setText(_translate("Homepage", "Sajin"))
        self.labelDisplayCarte1.setText(_translate("Homepage", "X"))
        self.labelCarte1.setText(_translate("Homepage", "Photos à trier"))
        self.labelDisplayCarte2.setText(_translate("Homepage", "Y"))
        self.labelCarte2.setText(_translate("Homepage", "RAW"))
        self.labelDisplayCarte3.setText(_translate("Homepage", "Z"))
        self.labelCarte3.setText(_translate("Homepage", "JPEG"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Homepage = QtWidgets.QMainWindow()
    ui = Ui_Homepage()
    ui.setupUi(Homepage)
    Homepage.show()
    sys.exit(app.exec_())
