# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FenetreTri.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SortingPage(object):
    def setupUi(self, SortingPage):
        SortingPage.setObjectName("SortingPage")
        SortingPage.resize(723, 495)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(SortingPage.sizePolicy().hasHeightForWidth())
        SortingPage.setSizePolicy(sizePolicy)
        self.widgetCentral = QtWidgets.QWidget(SortingPage)
        self.widgetCentral.setStyleSheet("*{\n"
"    color:#000;\n"
"    border:none;\n"
"}\n"
"QPushButton{\n"
"    padding: 9px 5px;\n"
"    text-align: left;\n"
"}\n"
"#menuGauche{\n"
"    background-color: #65132d;\n"
"}\n"
"#triBtn{\n"
"    background-color:#e5e5e5;\n"
"    padding: 10px 5px;\n"
"    text-align: left;\n"
"    border-top-left-radius: 15px;\n"
"}\n"
"#reglagesBtn, #renommageBtn, #sauvegardeBtn, #accueilBtn{\n"
"    color: #ffffff;\n"
"}\n"
"#partiePrincipale{\n"
"    background-color: #e5e5e5;\n"
"}\n"
"#separationBtn, #coherenceBtn, #rangementBtn, #suppressionBtn{\n"
"    background-color: white;\n"
"    color: black;\n"
"    border-radius: 10px;\n"
"    text-align: center;\n"
"}\n"
"#separationBtn:pressed, #coherenceBtn:pressed, #rangementBtn:pressed, #suppressionBtn:pressed{\n"
"    background-color: #5a0022;\n"
"    color: white;\n"
"    text-align: center;\n"
"}\n"
"#widgetReglages{\n"
"    background-color:#ffffff;\n"
"    border-radius:10px;\n"
"}\n"
"#saveBtn{\n"
"    border: 2px solid #e5e5e5;\n"
"    border-radius: 10px;\n"
"}\n"
"#saveBtn:pressed{\n"
"    background-color: #e5e5e5;\n"
"}\n"
"#progressBar{\n"
"    background-color: #e5e5e5;\n"
"}\n"
"#lineNomEvent, #lineNumPhotos{\n"
"    border: 1px solid #e5e5e5;\n"
"    border-radius: 4px;\n"
"}")
        self.widgetCentral.setObjectName("widgetCentral")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widgetCentral)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.menuGauche = QtWidgets.QWidget(self.widgetCentral)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.menuGauche.sizePolicy().hasHeightForWidth())
        self.menuGauche.setSizePolicy(sizePolicy)
        self.menuGauche.setStyleSheet("")
        self.menuGauche.setObjectName("menuGauche")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.menuGauche)
        self.horizontalLayout_4.setContentsMargins(10, 18, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.frameMenu = QtWidgets.QFrame(self.menuGauche)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameMenu.sizePolicy().hasHeightForWidth())
        self.frameMenu.setSizePolicy(sizePolicy)
        self.frameMenu.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameMenu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameMenu.setObjectName("frameMenu")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.frameMenu)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.accueilBtn = QtWidgets.QPushButton(self.frameMenu)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.accueilBtn.setFont(font)
        self.accueilBtn.setIconSize(QtCore.QSize(20, 20))
        self.accueilBtn.setObjectName("accueilBtn")
        self.verticalLayout_11.addWidget(self.accueilBtn)
        self.triBtn = QtWidgets.QPushButton(self.frameMenu)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.triBtn.setFont(font)
        self.triBtn.setObjectName("triBtn")
        self.verticalLayout_11.addWidget(self.triBtn)
        self.renommageBtn = QtWidgets.QPushButton(self.frameMenu)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.renommageBtn.setFont(font)
        self.renommageBtn.setObjectName("renommageBtn")
        self.verticalLayout_11.addWidget(self.renommageBtn)
        self.sauvegardeBtn = QtWidgets.QPushButton(self.frameMenu)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.sauvegardeBtn.setFont(font)
        self.sauvegardeBtn.setObjectName("sauvegardeBtn")
        self.verticalLayout_11.addWidget(self.sauvegardeBtn)
        self.reglagesBtn = QtWidgets.QPushButton(self.frameMenu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.reglagesBtn.sizePolicy().hasHeightForWidth())
        self.reglagesBtn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.reglagesBtn.setFont(font)
        self.reglagesBtn.setObjectName("reglagesBtn")
        self.verticalLayout_11.addWidget(self.reglagesBtn)
        self.horizontalLayout_4.addWidget(self.frameMenu, 0, QtCore.Qt.AlignTop)
        self.horizontalLayout.addWidget(self.menuGauche)
        self.partiePrincipale = QtWidgets.QWidget(self.widgetCentral)
        self.partiePrincipale.setObjectName("partiePrincipale")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.partiePrincipale)
        self.verticalLayout.setContentsMargins(10, 0, 10, 10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widgetEnTete = QtWidgets.QWidget(self.partiePrincipale)
        self.widgetEnTete.setObjectName("widgetEnTete")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widgetEnTete)
        self.horizontalLayout_2.setContentsMargins(0, 18, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.labelEnTete = QtWidgets.QLabel(self.widgetEnTete)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelEnTete.sizePolicy().hasHeightForWidth())
        self.labelEnTete.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Savoye LET")
        font.setPointSize(69)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.labelEnTete.setFont(font)
        self.labelEnTete.setTextFormat(QtCore.Qt.AutoText)
        self.labelEnTete.setScaledContents(False)
        self.labelEnTete.setObjectName("labelEnTete")
        self.horizontalLayout_2.addWidget(self.labelEnTete, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout.addWidget(self.widgetEnTete)
        self.btnFrame = QtWidgets.QFrame(self.partiePrincipale)
        self.btnFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.btnFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.btnFrame.setObjectName("btnFrame")
        self.gridLayout = QtWidgets.QGridLayout(self.btnFrame)
        self.gridLayout.setContentsMargins(50, 0, 50, 0)
        self.gridLayout.setHorizontalSpacing(100)
        self.gridLayout.setVerticalSpacing(12)
        self.gridLayout.setObjectName("gridLayout")
        self.separationBtn = QtWidgets.QPushButton(self.btnFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.separationBtn.sizePolicy().hasHeightForWidth())
        self.separationBtn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.separationBtn.setFont(font)
        self.separationBtn.setObjectName("separationBtn")
        self.gridLayout.addWidget(self.separationBtn, 0, 0, 1, 1)
        self.coherenceBtn = QtWidgets.QPushButton(self.btnFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.coherenceBtn.sizePolicy().hasHeightForWidth())
        self.coherenceBtn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.coherenceBtn.setFont(font)
        self.coherenceBtn.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.coherenceBtn.setObjectName("coherenceBtn")
        self.gridLayout.addWidget(self.coherenceBtn, 0, 1, 1, 1)
        self.rangementBtn = QtWidgets.QPushButton(self.btnFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rangementBtn.sizePolicy().hasHeightForWidth())
        self.rangementBtn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.rangementBtn.setFont(font)
        self.rangementBtn.setObjectName("rangementBtn")
        self.gridLayout.addWidget(self.rangementBtn, 1, 0, 1, 1)
        self.suppressionBtn = QtWidgets.QPushButton(self.btnFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.suppressionBtn.sizePolicy().hasHeightForWidth())
        self.suppressionBtn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.suppressionBtn.setFont(font)
        self.suppressionBtn.setObjectName("suppressionBtn")
        self.gridLayout.addWidget(self.suppressionBtn, 1, 1, 1, 1)
        self.verticalLayout.addWidget(self.btnFrame)
        self.widgetPrincipal = QtWidgets.QWidget(self.partiePrincipale)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widgetPrincipal.sizePolicy().hasHeightForWidth())
        self.widgetPrincipal.setSizePolicy(sizePolicy)
        self.widgetPrincipal.setObjectName("widgetPrincipal")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.widgetPrincipal)
        self.horizontalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.widgetReglages = QtWidgets.QWidget(self.widgetPrincipal)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widgetReglages.sizePolicy().hasHeightForWidth())
        self.widgetReglages.setSizePolicy(sizePolicy)
        self.widgetReglages.setObjectName("widgetReglages")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widgetReglages)
        self.gridLayout_2.setContentsMargins(12, 12, 0, 10)
        self.gridLayout_2.setVerticalSpacing(17)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frameReglagesGauche = QtWidgets.QFrame(self.widgetReglages)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameReglagesGauche.sizePolicy().hasHeightForWidth())
        self.frameReglagesGauche.setSizePolicy(sizePolicy)
        self.frameReglagesGauche.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameReglagesGauche.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameReglagesGauche.setObjectName("frameReglagesGauche")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frameReglagesGauche)
        self.verticalLayout_5.setContentsMargins(0, 0, 300, 12)
        self.verticalLayout_5.setSpacing(13)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.lineNomEvent = QtWidgets.QLineEdit(self.frameReglagesGauche)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineNomEvent.sizePolicy().hasHeightForWidth())
        self.lineNomEvent.setSizePolicy(sizePolicy)
        self.lineNomEvent.setInputMask("")
        self.lineNomEvent.setText("")
        self.lineNomEvent.setFrame(True)
        self.lineNomEvent.setObjectName("lineNomEvent")
        self.verticalLayout_5.addWidget(self.lineNomEvent)
        self.checkBox = QtWidgets.QCheckBox(self.frameReglagesGauche)
        self.checkBox.setObjectName("checkBox")
        self.verticalLayout_5.addWidget(self.checkBox)
        self.dateEdit = QtWidgets.QDateEdit(self.frameReglagesGauche)
        self.dateEdit.setCalendarPopup(True)
        self.dateEdit.setObjectName("dateEdit")
        self.verticalLayout_5.addWidget(self.dateEdit)
        self.lineNumPhotos = QtWidgets.QLineEdit(self.frameReglagesGauche)
        self.lineNumPhotos.setEnabled(True)
        self.lineNumPhotos.setObjectName("lineNumPhotos")
        self.verticalLayout_5.addWidget(self.lineNumPhotos)
        self.gridLayout_2.addWidget(self.frameReglagesGauche, 1, 0, 1, 1)
        self.labelReglages = QtWidgets.QLabel(self.widgetReglages)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelReglages.sizePolicy().hasHeightForWidth())
        self.labelReglages.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.labelReglages.setFont(font)
        self.labelReglages.setObjectName("labelReglages")
        self.gridLayout_2.addWidget(self.labelReglages, 0, 0, 1, 1, QtCore.Qt.AlignTop)
        self.horizontalLayout_12.addWidget(self.widgetReglages)
        self.verticalLayout.addWidget(self.widgetPrincipal)
        self.Statelabel = QtWidgets.QLabel(self.partiePrincipale)
        self.Statelabel.setObjectName("Statelabel")
        self.verticalLayout.addWidget(self.Statelabel)
        self.progressBar = QtWidgets.QProgressBar(self.partiePrincipale)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setKerning(True)
        self.progressBar.setFont(font)
        self.progressBar.setProperty("value", 25)
        self.progressBar.setTextVisible(False)
        self.progressBar.setInvertedAppearance(False)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout.addWidget(self.progressBar)
        self.horizontalLayout.addWidget(self.partiePrincipale)
        SortingPage.setCentralWidget(self.widgetCentral)

        self.retranslateUi(SortingPage)
        QtCore.QMetaObject.connectSlotsByName(SortingPage)

    def retranslateUi(self, SortingPage):
        _translate = QtCore.QCoreApplication.translate
        SortingPage.setWindowTitle(_translate("SortingPage", "MainWindow"))
        self.accueilBtn.setText(_translate("SortingPage", "Accueil"))
        self.triBtn.setText(_translate("SortingPage", "  Tri"))
        self.renommageBtn.setText(_translate("SortingPage", "Renommage    "))
        self.sauvegardeBtn.setText(_translate("SortingPage", "Sauvegarde"))
        self.reglagesBtn.setText(_translate("SortingPage", "Réglages"))
        self.labelEnTete.setText(_translate("SortingPage", "Sajin"))
        self.separationBtn.setText(_translate("SortingPage", "Séparation"))
        self.coherenceBtn.setText(_translate("SortingPage", "Cohérence"))
        self.rangementBtn.setText(_translate("SortingPage", "Rangement"))
        self.suppressionBtn.setText(_translate("SortingPage", "Suppression"))
        self.lineNomEvent.setPlaceholderText(_translate("SortingPage", "  Nom de l\'évènement"))
        self.checkBox.setText(_translate("SortingPage", "Mode Manuel"))
        self.lineNumPhotos.setPlaceholderText(_translate("SortingPage", "  Num des photos ( - )"))
        self.labelReglages.setText(_translate("SortingPage", "Réglages de rangement"))
        self.Statelabel.setText(_translate("SortingPage", "TextLabel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SortingPage = QtWidgets.QMainWindow()
    ui = Ui_SortingPage()
    ui.setupUi(SortingPage)
    SortingPage.show()
    sys.exit(app.exec_())
